### ISSUE TITLE
Work left to do

### ISSUE THREAD

**Issue by ericaxu** [ericaxu/hci#3]
Write a checklist for yourself!

**Comment by ericaxu** [comment]
- [x] Remove "Dashboard"
- [x] "Starred" should be a sidebar header just like "Conversation"
- [x] Sample starred conversations
- [x] Trigger upload
- [x] A way to hide right panel
- [x] Add reply to conversation history
- [x] Create conversation should create new item in sidebar
- [x] Fix resoure to convo panel switch
- [x] Members right panel

**Comment by markozhen** [comment]
- [x] Add Comment popup
- [x] "@" tagging
- [x] Main Panel padding
- [x] Right Panel switching
- [x] Files right panel
- [x] Live audio button (mute mic, sound volume buttons)
- [ ] Not yet Implemented popup error (for anything not finished / added)

Nice to haves
- [ ] Different convos (to show switching)
- [ ] Member profile right panel
- [ ] Settings, My Profile main panels
